[libraries]
androidPlugin = "com.android.tools.build:gradle:8.8.0"
gradleMavenPublishPlugin = "com.vanniktech:gradle-maven-publish-plugin:0.30.0"
spotlessPlugin = "com.diffplug.spotless:spotless-plugin-gradle:7.0.2"

googleJavaFormat = "com.google.googlejavaformat:google-java-format:1.25.2"
